=== plat956/4th_XMLParsers/src/main/resources/schema/devices-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/devices"
        xmlns:tns="http://www.example.com/devices"
        elementFormDefault="qualified">
    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="device">
        <sequence>
            <element name="name" type="string" />
            <element name="origin" type="tns:origin" />
            <element name="purchase-date" type="gYearMonth" />
            <element name="group" type="tns:deviceGroup" />
            <element name="price" type="tns:price" />
            <element name="critical" type="boolean" />
        </sequence>
        <attribute name="id" type="tns:deviceId" use="required" />
        <attribute name="vendor-site" type="" use="optional" default="https://device-support.com" />
    </complexType>

    <complexType name="embeddedDevice">
        <complexContent>
            <extension base="tns:device">
                <sequence>
                    <element name="type" type="tns:embeddedDeviceType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="portableDevice">
        <complexContent>
            <extension base="tns:device">
                <sequence>
                    <element name="rechargeable" type="boolean" />
                    <element name="protective-case" type="boolean" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="deviceId">
        <restriction base="ID">
            <pattern value="\w{4}-\d{6}-\d{2}" />
        </restriction>
    </simpleType>

    <simpleType name="origin">
        <restriction base="string">
            <enumeration value="Belarus" />
            <enumeration value="Ukraine" />
            <enumeration value="Japan" />
            <enumeration value="China" />
            <enumeration value="USA" />
        </restriction>
    </simpleType>

    <simpleType name="deviceGroup">
        <restriction base="string">
            <enumeration value="input" />
            <enumeration value="output" />
            <enumeration value="multimedia" />
            <enumeration value="others" />
        </restriction>
    </simpleType>

    <simpleType name="embeddedDeviceType">
        <restriction base="string">
            <enumeration value="RAM" />
            <enumeration value="CPU" />
            <enumeration value="Motherboard" />
            <enumeration value="Memory drive" />
        </restriction>
    </simpleType>

    <simpleType name="price">
        <restriction base="decimal">
            <minInclusive value="0.10" />
            <maxInclusive value="9999999.99" />
        </restriction>
    </simpleType>

    <element name="device" type="tns:device" abstract="true" />
    <element name="embedded-device" type="tns:embeddedDevice" substitutionGroup="tns:device" />
    <element name="portable-device" type="tns:portableDevice" substitutionGroup="tns:device" />
</schema>

=== plat956/4th_XMLParsers/src/test/resources/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices ../schema/devices-schema.xsd">

    <portable-device id="sn11-555555-01">
        <name>Logitech keyboard</name>
        <origin>China</origin>
        <purchase-date>2021-11</purchase-date>
        <group>input</group>
        <price>15.45</price>
        <critical>false</critical>
        <rechargeable>true</rechargeable>
        <protective-case>false</protective-case>
    </portable-device>

    <embedded-device id="sn99-123333-12">
        <name>Gigabyte motherboard</name>
        <origin>Japan</origin>
        <purchase-date>2010-03</purchase-date>
        <group>others</group>
        <price>243.75</price>
        <critical>true</critical>
        <type>Motherboard</type>
    </embedded-device>

</devices>

=== plat956/4th_XMLParsers/src/main/resources/data/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://www.example.com/devices"
          xsi:schemaLocation="http://www.example.com/devices ../schema/devices-schema.xsd">

    <portable-device id="sn11-555555-01">
        <name>Logitech keyboard</name>
        <origin>China</origin>
        <purchase-date>2021-11</purchase-date>
        <group>input</group>
        <price>15.45</price>
        <critical>false</critical>
        <rechargeable>true</rechargeable>
        <protective-case>false</protective-case>
    </portable-device>

    <portable-device id="sn11-555555-02">
        <name>Logitech mouse</name>
        <origin>China</origin>
        <purchase-date>2021-11</purchase-date>
        <group>input</group>
        <price>5.67</price>
        <critical>false</critical>
        <rechargeable>true</rechargeable>
        <protective-case>false</protective-case>
    </portable-device>

    <portable-device id="sn55-433421-11">
        <name>Apple trackpad</name>
        <origin>USA</origin>
        <purchase-date>2021-10</purchase-date>
        <group>input</group>
        <price>100.12</price>
        <critical>false</critical>
        <rechargeable>false</rechargeable>
        <protective-case>true</protective-case>
    </portable-device>

    <portable-device id="sn21-211233-14">
        <name>JBL soundbar</name>
        <origin>USA</origin>
        <purchase-date>2021-11</purchase-date>
        <group>output</group>
        <price>65.43</price>
        <critical>false</critical>
        <rechargeable>true</rechargeable>
        <protective-case>false</protective-case>
    </portable-device>

    <portable-device id="sn13-211233-14">
        <name>Unknown portable device</name>
        <origin>USA</origin>
        <purchase-date>2021-11</purchase-date>
        <group>output</group>
        <price>13.23</price>
        <critical>true</critical>
        <rechargeable>false</rechargeable>
        <protective-case>true</protective-case>
    </portable-device>

    <portable-device id="sn10-211233-14">
        <name>Unknown portable device</name>
        <origin>Japan</origin>
        <purchase-date>2020-12</purchase-date>
        <group>multimedia</group>
        <price>223.23</price>
        <critical>false</critical>
        <rechargeable>false</rechargeable>
        <protective-case>true</protective-case>
    </portable-device>

    <portable-device id="sn10-211333-14">
        <name>Unknown portable device</name>
        <origin>Belarus</origin>
        <purchase-date>2010-11</purchase-date>
        <group>multimedia</group>
        <price>17.33</price>
        <critical>false</critical>
        <rechargeable>true</rechargeable>
        <protective-case>true</protective-case>
    </portable-device>

    <portable-device id="sn09-211333-14">
        <name>Unknown portable device</name>
        <origin>Ukraine</origin>
        <purchase-date>2001-01</purchase-date>
        <group>multimedia</group>
        <price>5.30</price>
        <critical>false</critical>
        <rechargeable>false</rechargeable>
        <protective-case>false</protective-case>
    </portable-device>

    <embedded-device id="sn99-123333-12">
        <name>Gigabyte motherboard</name>
        <origin>Japan</origin>
        <purchase-date>2010-03</purchase-date>
        <group>others</group>
        <price>243.75</price>
        <critical>true</critical>
        <type>Motherboard</type>
    </embedded-device>

    <embedded-device id="sn99-123333-32">
        <name>ASUS motherboard</name>
        <origin>Japan</origin>
        <purchase-date>2013-04</purchase-date>
        <group>others</group>
        <price>313.75</price>
        <critical>true</critical>
        <type>Motherboard</type>
    </embedded-device>

    <embedded-device id="sn99-123333-22">
        <name>Intel Core I5 cpu</name>
        <origin>USA</origin>
        <purchase-date>2020-01</purchase-date>
        <group>others</group>
        <price>130.00</price>
        <critical>true</critical>
        <type>CPU</type>
    </embedded-device>

    <embedded-device id="sn53-123333-22">
        <name>Samsung SSD Drive</name>
        <origin>Japan</origin>
        <purchase-date>2021-03</purchase-date>
        <group>others</group>
        <price>91.23</price>
        <critical>true</critical>
        <type>Memory drive</type>
    </embedded-device>

    <embedded-device id="sn53-555678-22">
        <name>LG RAM</name>
        <origin>Japan</origin>
        <purchase-date>2021-10</purchase-date>
        <group>others</group>
        <price>45.12</price>
        <critical>true</critical>
        <type>RAM</type>
    </embedded-device>

    <embedded-device id="sn89-344344-22">
        <name>Unknown embedded device</name>
        <origin>Japan</origin>
        <purchase-date>2021-10</purchase-date>
        <group>multimedia</group>
        <price>100.01</price>
        <critical>false</critical>
        <type>Memory drive</type>
    </embedded-device>

    <embedded-device id="sn89-344344-23">
        <name>Unknown embedded device</name>
        <origin>Belarus</origin>
        <purchase-date>2021-11</purchase-date>
        <group>multimedia</group>
        <price>32.01</price>
        <critical>false</critical>
        <type>Memory drive</type>
    </embedded-device>

    <embedded-device id="sn53-555678-24">
        <name>LG bluetooth chip</name>
        <origin>Japan</origin>
        <purchase-date>2021-10</purchase-date>
        <group>others</group>
        <price>15.12</price>
        <critical>false</critical>
        <type>Motherboard</type>
    </embedded-device>

</devices>
